# Build stage: install dependencies and compile the production Next.js bundle.
FROM node:22-alpine AS builder

WORKDIR /app

# Copy dependency manifests first so Docker can reuse this layer when only
# application source files change.
COPY package*.json ./

# `npm ci` installs the exact versions from package-lock.json and fails when
# package.json and the lock file disagree.
RUN npm ci

# API_URL is evaluated by next.config.mjs while `next build` generates rewrites.
# The default hostname matches the future backend service in Docker Compose.
ARG API_URL=http://backend:8000
ENV API_URL=$API_URL

# These values are intentionally embedded into browser JavaScript by Next.js.
# Never pass passwords or private API secrets through NEXT_PUBLIC_* arguments.
ARG NEXT_PUBLIC_API_URL=/backend
ARG NEXT_PUBLIC_GOOGLE_CLIENT_ID
ARG NEXT_PUBLIC_SCOPE=https://www.googleapis.com/auth/calendar
ARG NEXT_PUBLIC_REDIRECT_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL \
    NEXT_PUBLIC_GOOGLE_CLIENT_ID=$NEXT_PUBLIC_GOOGLE_CLIENT_ID \
    NEXT_PUBLIC_SCOPE=$NEXT_PUBLIC_SCOPE \
    NEXT_PUBLIC_REDIRECT_URL=$NEXT_PUBLIC_REDIRECT_URL

# Disable anonymous telemetry in both CI and container builds.
ENV NEXT_TELEMETRY_DISABLED=1

COPY . .

RUN npm run build

# Runtime stage: contains only the standalone production server and its assets.
FROM node:22-alpine AS runner

WORKDIR /app

# Use production behavior and listen on every container interface.
ENV NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1 \
    HOSTNAME=0.0.0.0 \
    PORT=3000

# Do not run the internet-facing Next.js process as root. Limiting the process
# to an unprivileged user reduces the impact of an application vulnerability.
RUN addgroup --system --gid 1001 nodejs \
    && adduser --system --uid 1001 --ingroup nodejs nextjs

# `output: "standalone"` creates a minimal server with only the runtime files
# and dependencies needed in production.
COPY --from=builder --chown=nextjs:nodejs /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Drop root privileges before starting the application.
USER nextjs

# EXPOSE documents the listening port; Compose still decides host publishing.
EXPOSE 3000

# server.js is generated by the Next.js standalone build.
CMD ["node", "server.js"]
